parameters:
- name: resource
  type: object
- name: globalConfiguration
  type: object

jobs:
  - job: BuildJob
    variables:
      BuildPlatform: 'Any CPU'
      BuildConfiguration: 'Release'
    displayName: Build Job
    steps:
      - checkout: self
        persistCredentials: true

      - powershell: Write-Host ${{ parameters.resource.tests.testFilesToRun }}

      - task: AzurePowerShell@4
        displayName: Running Unit Tests
        inputs:
          azureSubscription: AzureServiceConnection
          scriptType: "FilePath"
          scriptPath: $(Build.SourcesDirectory)/src/azureDevOps/pipeline/run.pipeline.tests.ps1
          # scriptArguments: -TestResultsDirectory "$(Build.ArtifactStagingDirectory)/testResults/" -TestScripts "$(Build.SourcesDirectory)/src/azureDevOps/pipeline/pipeline.tests.ps1"
          scriptArguments: -TestResultsDirectory "$(Build.ArtifactStagingDirectory)/testResults/" -TestScripts "${{ parameters.resource.tests.testFilesToRun }}"
          azurePowerShellVersion: "latestVersion"
          errorActionPreference: "continue"
        env:
          # secrets needs to be mapped as env variables
          personalAccessToken: ${{ parameters.globalConfiguration.personalAccessToken }}
          customModulesDirectory: ${{ parameters.globalConfiguration.customModulesDirectory }}
          orgUrl: ${{ parameters.globalConfiguration.orgUrl }}
          testsTeamProject: ${{ parameters.globalConfiguration.testsTeamProject }}
          yamlFilePath: ${{ parameters.resource.tests.yamlFilePath }}
          pipelineName: ${{ parameters.resource.tests.pipelineName }}
          repository: ${{ parameters.globalConfiguration.repository }}
          branch: ${{ parameters.globalConfiguration.branch }}
          skipTearDown: false
          serviceConnectionId: ${{ parameters.globalConfiguration.serviceConnectionId }}
          timeoutMinutes: ${{ parameters.resource.tests.timeoutMinutes }}
          testFilesToRun: ${{ parameters.resource.tests.testFilesToRun }}
          # pipelineId: ${{ parameters.resource.tests.pipelineId }}

      - task: PublishTestResults@2
        inputs:
          testRunner: "NUnit" 
          testResultsFiles: "$(Build.ArtifactStagingDirectory)/testResults/**/testResults.xml"
          testRunTitle: "PS_Win2016_Unit"
          failTaskOnFailedTests: true
        displayName: "Publish Unit Test Results"
        condition: in(variables['Agent.JobStatus'], 'Succeeded', 'SucceededWithIssues', 'Failed')

      - task: PublishCodeCoverageResults@1
        inputs:
          summaryFileLocation: "$(Build.ArtifactStagingDirectory)/testResults/**/coverage.xml"
          failIfCoverageEmpty: false
        displayName: "Publish Unit Test Code Coverage"
        condition: and(in(variables['Agent.JobStatus'], 'Succeeded', 'SucceededWithIssues', 'Failed'), eq(variables['System.PullRequest.IsFork'], false))
        enabled: false