# If you are using this example in your oun repository, 
# you need to uncomment the lines below:
# resources:
#   repositories:
#   - repository: UDP
#     type: github
#     endpoint: devopsnights
#     name: devopsnights/UDP
#     ref: refs/heads/main

trigger:
  - main
  - feature/*

# trigger:
#   branches:
#     include:
#     - main
#     - feature/*
  # paths:
  #   include:
  #   - examples/sqlserver

pool:
  vmImage: 'windows-latest'

extends:
  # If you are using this example in your oun repository, 
  # you need to uncomment the next line and comment the line streight below
  #template: src\orchestrator.yml@UDP 
  template: ..\..\src\orchestrator.yml
  parameters:
    serviceConnection: 'AzureServiceConnection'
    environments:
      - dev
      # - uat
      # - prd
    configuration:
      buildOnly: false
      resources:
        - type: sqlserver
          enabled: true
          solutionFilter: '**\sql-template.sln'
          deployment:
            type: azureWebApp
            name: wa-udp-dotnetcore-windows
            infrastructure:
              enabled: false
            application:
              enabled: true
              serverName: 'sql-udp.database.windows.net'
              databaseName: 'sqludp'
              sqlUsername: 'wesley'
              sqlPassword: '$(sqlPassword)'