parameters:
- name: solutionFilter
  type: string
  default: ''


jobs:
  - job: BuildJob
    variables:
      BuildPlatform: 'Any CPU'
      BuildConfiguration: 'Release'
    displayName: Build Job
    steps:

      - task: VSBuild@1
        inputs:
          ${{ if eq(parameters.solutionFilter, '') }}:
            solution: '**\*.sln'
          ${{ if ne(parameters.solutionFilter, '') }}:
            solution: ${{ parameters.solutionFilter }}
          msbuildArgs: '/p:OutDir=$(Pipeline.Workspace)'

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Pipeline.Workspace)'
          artifact: 'drop'
          publishLocation: 'pipeline'