parameters:
- name: serviceConnection
  type: string
- name: resource
  type: object
- name: environment
  type: string

jobs:
  - deployment: 
    displayName: Azure Data Factory Deployment
    environment: ${{ parameters.environment }}
    variables:
      dataFactoryName: adf-quickstart-dev
      subscriptionId: 337ba254-3aa0-4551-ba8e-89debefaa373
    pool:
      vmImage: 'vs2017-win2016'
    strategy:
      runOnce:
        preDeploy:
          steps:
            - task: DownloadPipelineArtifact@2 #downloading artifacts created in build stage
              inputs:
                source: 'current'
                path: '$(Pipeline.Workspace)'
          
            - task: AzureResourceManagerTemplateDeployment@3
              displayName: Creating ADF Infrastructure by IaC
              inputs:
                deploymentScope: 'Resource Group'
                azureResourceManagerConnection: '${{ parameters.serviceConnection }}'
                subscriptionId: '$(subscriptionId)'
                action: 'Create Or Update Resource Group'
                resourceGroupName: 'RG-Datafactory'
                location: 'northeurope'
                templateLocation: 'Linked artifact'
                csmFile: '$(Pipeline.Workspace)/datafactory/infrastructure/azure-datafactory.json '
                # overrideParameters: -dataFactoryName $(dataFactoryName) -environment ${{ parameters.environment }}
                overrideParameters: >
                  -dataFactoryName $(dataFactoryName) 
                  -environment ${{ parameters.environment }}
                  -repositoryType ${{ parameters.resource.deployment.infrastructure.repositoryType }}
                  -repositoryName ${{ parameters.resource.deployment.infrastructure.repositoryName }}
                  -accountName ${{ parameters.resource.deployment.infrastructure.accountName }}
                  -collaborationBranch ${{ parameters.resource.deployment.infrastructure.collaborationBranch }}
                  -rootFolder ${{ parameters.resource.deployment.infrastructure.rootFolder }}
                deploymentMode: 'Incremental'
                deploymentOutputs: 'ArmOutputs'

        deploy:
          steps:
            - task: AzureResourceManagerTemplateDeployment@3
              displayName: 'Deploying ADF Artificats'
              inputs:
                deploymentScope: 'Resource Group'
                azureResourceManagerConnection: ${{ parameters.serviceConnection }}
                subscriptionId: $(subscriptionId)
                action: 'Create Or Update Resource Group'
                resourceGroupName: 'RG-Datafactory'
                location: 'northeurope'
                templateLocation: 'Linked artifact'
                csmFile: '$(Pipeline.Workspace)/datafactory/application/ARMTemplateForFactory.json'
                csmParametersFile: '$(Pipeline.Workspace)/datafactory/application/ARMTemplateParametersForFactory.json'
                overrideParameters: '-factoryName $(dataFactoryName)'
                deploymentMode: 'Incremental'