trigger:
  branches:
    include:
    - main
  
pool:
  vmImage: 'windows-latest'

jobs:
  - job: runTests
    steps:    
      - checkout: self
        persistCredentials: true
      
      - task: AzurePowerShell@4
        inputs:
          azureSubscription: $(azureSubscription)
          scriptType: "FilePath"
          scriptPath: $(Build.SourcesDirectory)\examples\run.tests
          scriptArguments:
          azurePowerShellVersion: "latestVersion"
          errorActionPreference: "continue"

     
      
      - powershell: Get-ChildItem $(Build.SourcesDirectory) -recurse
       