parameters:
- name: serviceConnection
  type: string
- name: resource
  type: object
- name: environment
  type: string
- name: globalConfiguration
  type: object

jobs:
  - deployment: 
    displayName: Azure Web App Deployment
    environment: develop
    strategy:
      runOnce:
        preDeploy:
          steps:
            - template: ../appConfiguration/azure-appConfiguration-pullSecrets-jobs.yml
              parameters:
                environment: ${{ parameters.environment }}        
                globalConfiguration: ${{ parameters.globalConfiguration }}
                serviceConnection: ${{ parameters.serviceConnection }}

            - task: DownloadPipelineArtifact@2 #downloading artifacts created in build stage
              inputs:
                source: 'current'
                path: '$(Pipeline.Workspace)'

            - powershell: Get-ChildItem $(Pipeline.Workspace) -Recurse 
          
            - task: AzureResourceManagerTemplateDeployment@3
              displayName: Creating App Service Infrastructure by IaC
              inputs:
                deploymentScope: 'Resource Group'
                azureResourceManagerConnection: '${{ parameters.serviceConnection }}'
                subscriptionId: ${{ parameters.globalConfiguration.subscriptionId }}
                action: 'Create Or Update Resource Group'
                resourceGroupName: ${{ parameters.globalConfiguration.resourceGroupName }}
                location: ${{ parameters.globalConfiguration.location }}
                templateLocation: 'Linked artifact'
                csmFile: '$(Pipeline.Workspace)/${{ parameters.resource.type }}/infrastructure/azure-appservice.json'
                overrideParameters: >
                  -servicePlanName ${{ parameters.resource.deployment.infrastructure.servicePlanName }} 
                  -siteName ${{ parameters.resource.deployment.name }} 
                deploymentMode: 'Incremental'
                deploymentOutputs: 'ArmOutputs'

        deploy:
          steps:

            - template: ../appConfiguration/azure-appConfiguration-pullSecrets-jobs.yml
              parameters:
                environment: ${{ parameters.environment }}        
                globalConfiguration: ${{ parameters.globalConfiguration }}
                serviceConnection: ${{ parameters.serviceConnection }}
            
            - task: DownloadBuildArtifacts@0
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: ${{ parameters.resource.type }}
                downloadPath: '$(System.ArtifactsDirectory)'
            
            - task: AzureRmWebAppDeployment@4
              inputs:
                ConnectionType: 'AzureRM'
                azureSubscription: ${{ parameters.serviceConnection }}
                appType: 'webApp'
                WebAppName: ${{ parameters.resource.deployment.name }} 
                packageForLinux: '$(System.ArtifactsDirectory)/**/*.zip'