parameters:
- name: resource
  type: object
- name: configuration
  type: object

jobs:
  - job: BuildJob
    variables:
      BuildPlatform: 'Any CPU'
      BuildConfiguration: 'Release'
    displayName: Build Job
    steps:
      - checkout: self
        persistCredentials: true
      
      - powershell: Write-Host ${{ parameters.resource.personalAccessToken }}

      - task: AzurePowerShell@4
        inputs:
          azureSubscription: AzureServiceConnection
          scriptType: "FilePath"
          scriptPath: $(Build.SourcesDirectory)\examples\run.tests.ps1
          scriptArguments:
          azurePowerShellVersion: "latestVersion"
          errorActionPreference: "continue"
        env:
          # secrets needs to be mapped as env variables
          personalAccessToken: ${{ parameters.resource.personalAccessToken }}
          customModulesDirectory: ${{ parameters.configuration.customModulesDirectory }}
          orgUrl: ${{ parameters.configuration.orgUrl }}
          teamProject: ${{ parameters.configuration.teamProject }}
          yamlFilePath: ${{ parameters.resource.yamlFilePath }}
          pipelineId: ${{ parameters.resource.pipelineId }}