trigger:
- main
- feature/*

pool:
  vmImage: ubuntu-latest

variables:
  BuildPlatform: 'Any CPU'
  BuildConfiguration: 'Release'

jobs:
  - job: build
    steps:    
      - task: UseDotNet@2
        displayName: 'Install .NET Core SDK'
        inputs:
          version: 5.0.x
          performMultiLevelLookup: true

      - task: DotNetCoreCLI@2
        displayName: Publish
        inputs:
          command: publish
          publishWebProjects: True
          arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory) --self-contained true --runtime win-x86'
          zipAfterPublish: True

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact'
        inputs:
          PathtoPublish: '$(build.artifactstagingdirectory)'
        condition: succeededOrFailed()

  - deployment: 
    displayName: Azure Web App Deployment
    environment: develop
    dependsOn: build
    strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadBuildArtifacts@0
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'drop'
                downloadPath: '$(System.ArtifactsDirectory)'
            
            - task: AzureWebApp@1
              inputs:
                azureSubscription: 'AzureServiceConnection'
                appName: 'wa-udp-dotnetcore'
                package: $(System.ArtifactsDirectory)/**/*.zip
            
            # - task: AzureRmWebAppDeployment@4
            #   inputs:
            #     ConnectionType: 'AzureRM'
            #     azureSubscription: 'AzureServiceConnection'
            #     appType: 'webApp'
            #     WebAppName: 'webAppUDP'
            #     packageForLinux: '$(System.ArtifactsDirectory)/**/*.zip'