parameters:
- name: resourceType 
  type: string 
- name: webAppName 
  type: string
- name: serviceConnection
  type: string
  
jobs:
  - ${{ if eq(parameters.resourceType, 'dotnetcore') }}:    
      - template: .\build\dotnetcore-build-jobs.yml
  
  - ${{ if eq(parameters.resourceType, 'nodejs') }}:
      - template: .\build\nodejs-build-jobs.yml 

  - template: .\deploy\azure-webapp-deploy-jobs.yml
    parameters:
      webAppName: ${{ parameters.webAppName }}
      serviceConnection: ${{ parameters.serviceConnection }}