parameters:
- name: serviceConnection
  default: ''  
  type: string
- name: configuration
  type: object
- name: environments 
  type: object


stages:
- stage: build
  jobs:
    # iterate in all resources defined on consumer YAML
    - ${{ each resource in parameters.configuration.resources }}:
        - ${{ if eq(resource.enabled, 'true') }}:
            - ${{ if eq(resource.type, 'dotnetCore') }}:
              - template: ./dotnetcore/dotnetcore-build-jobs.yml
            - ${{ if eq(resource.type, 'nodejs') }}:
              - template: ./nodejs/nodejs-build-jobs.yml
            - ${{ if eq(resource.type, 'sqlserver') }}:
              - template: ./sqlserver/sqlserver-build-jobs.yml
                parameters:
                  resource: ${{ resource }}
            - ${{ if eq(resource.type, 'azuredatafactory') }}:
              - template: ./cloud/azure/datafactory/azure-datafactory-build-jobs.yml
                parameters:
                  resource: ${{ resource }}
                  serviceConnection: ${{ parameters.serviceConnection }}

- ${{ if ne(parameters.configuration.buildOnly, 'false') }}:
# iterate environment defined on consumer YAML
    - ${{ each env in parameters.environments }}:

        - stage:  ${{ env }}
          # enables depency according which branch triggered the process, using gitflow strategy
          ${{ if eq(env, 'dev') }}:
            condition: >-
              and( succeeded(),
                or( eq(variables['Build.SourceBranch'], 'refs/heads/develop'),
                    startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'),
                    startsWith(variables['Build.SourceBranch'], 'refs/heads/users/')
                  )
                )
            dependsOn: build
          ${{ if eq(env, 'uat') }}:
              condition: >-
                and( succeeded(),
                  or( startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'),
                      startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'),
                      startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/')
                    )
                  )
              dependsOn: build
          ${{ if eq(env, 'prd') }}:
              condition: >-
                and( succeeded(),
                  or( startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'),
                      startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/')
                    )
                  )
              dependsOn: uat

          jobs:
            # iterate in all resources defined on consumer YAML
            - ${{ each resource in parameters.configuration.resources }}:
                # check if deployment is enabled for this resource
                - ${{ if and(eq(resource.enabled, 'true'), eq(resource.deployment.application.enabled, 'true')) }}:
                    - ${{ if eq(resource.type, 'dotnetCore') }}:
                        - template: ./dotnetcore/dotnetcore-deploy-jobs.yml
                          parameters:
                            serviceConnection: ${{ parameters.serviceConnection }}
                            resource: ${{ resource }}
                    - ${{ if eq(resource.type, 'sqlServer') }}:
                        - template: ./sqlserver/sqlserver-deploy-jobs.yml
                          parameters:
                            serviceConnection: ${{ parameters.serviceConnection }}
                            resource: ${{ resource }}
                    - ${{ if eq(resource.type, 'azuredatafactory') }}:
                        - template: ./cloud/azure/datafactory/azure-datafactory-deploy-jobs.yml
                          parameters:
                            resource: ${{ resource }}
                            serviceConnection: ${{ parameters.serviceConnection }}