parameters:
- name: serviceConnection
  type: string
- name: environment
  type: string
- name: globalConfiguration
  type: object

steps:
  - task: AzureAppConfiguration@3
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      ConfigstoreName: ${{ parameters.globalConfiguration.appConfigurationName }}
      KeyFilter: '*'
      Label: ${{ parameters.environment }}
           