parameters:
- name: serviceConnection
  type: string
- name: resource
  type: object
- name: environment
  type: string


steps:
  - task: AzureAppConfiguration@3
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      ConfigstoreName: 'UDP-Tests'
      KeyFilter: '*'
      Label: ${{ parameters.environment }}
  
  - powershell: "Get-Item -Path Env:"
           