parameters:
  - name: serviceConnection
    type: string
  - name: resource
    type: object

jobs:
  - job: BuildJob
    variables:
      BuildPlatform: 'Any CPU'
      BuildConfiguration: 'Release'
    displayName: Build Job
    steps:

      - task: DotNetCoreCLI@2
        displayName: Restore
        inputs:
          command: restore
          projects:  |
            **\*.csproj

      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          projects:  |
            **\*.csproj
            arguments: '--configuration $(BuildConfiguration)'

      - task: DotNetCoreCLI@2
        displayName: Test
        inputs:
          command: test
          projects: '**/*[Tt]ests/*.csproj'
          arguments: '--configuration $(BuildConfiguration)'

      - task: DotNetCoreCLI@2
        displayName: Publish
        inputs:
          command: publish
          publishWebProjects: True
          arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
          zipAfterPublish: True

      - ${{ if eq(parameters.resource.deployment.type, 'azureWebApp') }}:
          - template: ../cloud/azure/bicep/azure-bicep-build-tasks.yml
            parameters:
              serviceConnection: ${{ parameters.serviceConnection }}
              bicepFilePath: ${{ parameters.resource.deployment.infrastructure.iacFilePath }}

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact'
        inputs:
          PathtoPublish: '$(build.artifactstagingdirectory)'
        condition: succeededOrFailed()